x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - D:/storage/game-stream-trends/minio1/data1:/data1
      - D:/storage/game-stream-trends/minio1/data2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - D:/storage/game-stream-trends/minio2/data1:/data1
      - D:/storage/game-stream-trends/minio2/data2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - D:/storage/game-stream-trends/minio3/data1:/data1
      - D:/storage/game-stream-trends/minio3/data2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - D:/storage/game-stream-trends/minio4/data1:/data1
      - D:/storage/game-stream-trends/minio4/data2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: